[workspace]
members = ["beacon-api", "beacon-arrow-netcdf", "beacon-arrow-odv", "beacon-common", "beacon-config", "beacon-core", "beacon-functions", "beacon-query", "beacon-planner", "beacon-data-lake", "beacon-formats", "beacon-arrow-zarr"]

[workspace.dependencies]
tokio = { version = "1.47.1", features = ["full"] }
tokio-util = {version ="0.7.13", features = ["io"]}
futures = "0.3.31"
futures-util = "0.3.31"
async-trait = "0.1.85"
bytes = "1.9.0"
parking_lot = { version = "0.12.3", features = ["send_guard", "serde"] }
either = "1.15.0"

utoipa = { version= "=5.3.1", features = ["chrono","preserve_order", "preserve_path_order","rc_schema", "axum_extras"] }
utoipa-axum = "0.2.0"
utoipa-scalar = { version = "0.3.0", features = ["axum"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }

serde = { version = "^1.0.2", features = ["rc", "derive"] }
serde_json = "=1.0.120"
anyhow = "1.0.95"
thiserror = "2.0.12"

tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
glob = "0.3.2"
tempfile = "3.15.0"
typetag = "0.2.19"
indexmap = { version = "2.7.1", features = ["serde"]}
chrono = { version = "0.4.41", features = ["serde"] }
crossbeam = "0.8.4"

datafusion = "49.0.0"
object_store = { version = "0.12.3", features = ["aws"] }

arrow = { version = "^55.2.0", features = ["prettyprint"]}
arrow-schema = { version = "^55.2.0", features = ["serde"] }
parquet = { version = "^55.2.0", features = ["async"] }
geoarrow = { version = "=0.4.0" }
geoarrow-array = "=0.4.0"
geoparquet = "0.4.0"
