[workspace]
members = ["beacon-api", "beacon-config", "beacon-core", "beacon-logger"]

[workspace.dependencies]
tokio = { version = "1.43.0", features = ["full"] }

utoipa = { version= "=5.3.1", features = ["chrono","preserve_order", "preserve_path_order","rc_schema", "axum_extras"] }
utoipa-axum = "0.2.0"
utoipa-scalar = { version = "0.3.0", features = ["axum"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }

serde = "=1.0.200"
serde_json = "=1.0.120"
anyhow = "1.0.95"

tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }