[package]
name = "beacon-sources"
version = "1.1.0"
edition = "2021"

[dependencies]
futures = { workspace=true}
futures-util = { workspace=true}
async-trait = { workspace=true}
datafusion = { workspace=true}
arrow = { workspace=true }
anyhow = { workspace=true}
glob = { workspace = true}
tokio = { workspace = true }
indexmap = { workspace = true }
object_store = { workspace = true }
async-stream = "0.3.6"
nd-arrow-array = { git = "https://github.com/robinskil/nd-arrow-array.git", branch = "main" }
tracing = { workspace=true }
serde = { workspace=true}
utoipa = { workspace=true}
tempfile = { workspace=true}
regex = "1.11.1"
geoarrow = { version = "=0.4.0-beta.3", features = ["parquet"] }


# Local dependencies
beacon-config = { path = "../beacon-config" }
beacon-arrow-netcdf = { path = "../beacon-arrow-netcdf" }
beacon-arrow-odv = { path = "../beacon-arrow-odv" }
beacon-common = { path = "../beacon-common" }