[package]
name = "beacon-api"
version = "1.2.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["tracing"] }
tower-http = { version = "0.6.1", features = ["trace", "cors"] }
tikv-jemallocator = "0.6.0"
base64 = "0.22.1"

futures = { workspace = true }
futures-util = { workspace = true }

utoipa = { workspace = true }
utoipa-axum = { workspace = true }
utoipa-scalar = { workspace = true }
utoipa-swagger-ui = { workspace = true }
tokio = { workspace = true}
tokio-util = { workspace = true}
serde = { workspace = true}
anyhow = { workspace = true}
arrow = { workspace = true}
arrow-schema = { workspace = true}
uuid = { version = "1.16.0" }
tracing = { workspace = true}
tracing-subscriber = { workspace = true}

# Local dependencies
beacon-config = { path = "../beacon-config" }
beacon-core = { path = "../beacon-core" }
beacon-query = { path = "../beacon-query" }
beacon-planner = { path = "../beacon-planner" }
beacon-functions = { path = "../beacon-functions" }
