"""Type stubs for the compiled extension `beacondb._beacondb`.

Hand-maintained: the extension is built by PyO3, so these describe its surface for editors and
type checkers. Columnar returns (`pyarrow.Table`, `pandas.DataFrame`, `polars.DataFrame`,
`pyarrow.RecordBatchReader`) are typed `Any` so the stubs pull in no optional dependency.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------------------------
# Exceptions (PEP 249 tree)
# ---------------------------------------------------------------------------------------------

class Warning(Exception): ...
class Error(Exception): ...
class InterfaceError(Error): ...
class DatabaseError(Error): ...
class DataError(DatabaseError): ...
class OperationalError(DatabaseError): ...
class IntegrityError(DatabaseError): ...
class InternalError(DatabaseError): ...
class ProgrammingError(DatabaseError): ...
class NotSupportedError(DatabaseError): ...
class NotPermittedError(ProgrammingError): ...

# ---------------------------------------------------------------------------------------------
# Result — the materialized result of a statement or json_query
# ---------------------------------------------------------------------------------------------

class Result:
    @property
    def description(self) -> list[tuple[str, str, None, None, None, None, bool]]: ...
    @property
    def rowcount(self) -> int: ...
    @property
    def columns(self) -> list[str]: ...
    @property
    def types(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def fetchmany(self, size: int = 1) -> list[tuple[Any, ...]]: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...
    def arrow(self) -> Any: ...
    def df(self) -> Any: ...
    def fetchdf(self) -> Any: ...
    def pl(self) -> Any: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> Any: ...

# ---------------------------------------------------------------------------------------------
# Relation — a lazily-composed query
# ---------------------------------------------------------------------------------------------

class Relation:
    # terminal — materialize
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def fetchmany(self, size: int = 1) -> list[tuple[Any, ...]]: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...
    def arrow(self) -> Any: ...
    def fetch_arrow_table(self) -> Any: ...
    def to_arrow_table(self) -> Any: ...
    def df(self) -> Any: ...
    def to_df(self) -> Any: ...
    def fetchdf(self) -> Any: ...
    def pl(self) -> Any: ...
    # streaming: a pyarrow.RecordBatchReader pulled from the engine on demand (memory-bounded)
    def record_batch(self, batch_size: int | None = None) -> Any: ...
    def fetch_record_batch(self, batch_size: int | None = None) -> Any: ...
    def fetch_arrow_reader(self, batch_size: int | None = None) -> Any: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> Any: ...
    # terminal — file sinks
    def to_parquet(self, path: str) -> None: ...
    def to_csv(self, path: str) -> None: ...
    def to_arrow_ipc(self, path: str) -> None: ...
    def to_ipc(self, path: str) -> None: ...
    def to_netcdf(self, path: str) -> None: ...
    def to_hdf5(self, path: str) -> None: ...
    def to_nd_netcdf(self, path: str, dimensions: list[str]) -> None: ...
    def to_geoparquet(
        self, path: str, longitude: str | None = None, latitude: str | None = None
    ) -> None: ...
    def to_odv(
        self,
        path: str,
        *,
        longitude: str | None = None,
        latitude: str | None = None,
        depth: str | None = None,
        time: str | None = None,
        key: str | None = None,
        qf_schema: str | None = None,
    ) -> None: ...
    # metadata / introspection
    @property
    def sql(self) -> str: ...
    @property
    def columns(self) -> list[str]: ...
    @property
    def types(self) -> list[str]: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    def __len__(self) -> int: ...
    def explain(self, analyze: bool = False) -> str: ...
    def show(self, limit: int = 10) -> None: ...
    # DDL from a relation
    def create(self, name: str) -> Relation: ...
    def create_view(self, name: str) -> Relation: ...

# ---------------------------------------------------------------------------------------------
# Connection
# ---------------------------------------------------------------------------------------------

class Connection:
    # DB-API execution
    def execute(self, query: str, parameters: list[Any] | tuple[Any, ...] | None = None) -> Connection: ...
    def executemany(self, query: str, seq_of_parameters: Any) -> Connection: ...
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def fetchmany(self, size: int = 1) -> list[tuple[Any, ...]]: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...
    @property
    def description(self) -> list[tuple[str, str, None, None, None, None, bool]] | None: ...
    @property
    def rowcount(self) -> int: ...

    # lazy relational entry points
    def sql(self, query: str) -> Relation: ...
    def query(self, query: str) -> Relation: ...
    def table(self, name: str) -> Relation: ...
    def view(self, name: str) -> Relation: ...

    # readers (resolved from the catalog via __getattr__; declared here for editors).
    # Positional args are the path/glob then any format options; options may also be passed by
    # keyword (matched to the reader's declared parameters), and `columns=[...]` projects columns.
    def read(self, function: str, *args: Any, **kwargs: Any) -> Relation: ...
    def read_parquet(self, *args: Any, **kwargs: Any) -> Relation: ...
    def read_csv(self, *args: Any, **kwargs: Any) -> Relation: ...
    def read_arrow(self, *args: Any, **kwargs: Any) -> Relation: ...
    def read_netcdf(self, *args: Any, **kwargs: Any) -> Relation: ...
    def read_hdf5(self, *args: Any, **kwargs: Any) -> Relation: ...
    def read_zarr(self, *args: Any, **kwargs: Any) -> Relation: ...
    def read_delta(self, *args: Any, **kwargs: Any) -> Relation: ...
    def read_iceberg(self, *args: Any, **kwargs: Any) -> Relation: ...
    def read_geoparquet(self, *args: Any, **kwargs: Any) -> Relation: ...
    def read_odv_ascii(self, *args: Any, **kwargs: Any) -> Relation: ...
    def read_tiff(self, *args: Any, **kwargs: Any) -> Relation: ...
    def read_bbf(self, *args: Any, **kwargs: Any) -> Relation: ...
    def list_datasets(self, *args: Any, **kwargs: Any) -> Relation: ...
    def browse_datasets(self, *args: Any, **kwargs: Any) -> Relation: ...
    def table_functions(self) -> list[str]: ...
    # attach a remote Beacon instance as a catalog (queryable as name.schema.table, with pushdown)
    def attach(
        self,
        name: str,
        url: str,
        *,
        token: str | None = None,
        username: str | None = None,
        password: str | None = None,
        secret: str | None = None,
        tls: bool = False,
    ) -> None: ...
    def detach(self, name: str) -> bool: ...
    def attached(self) -> list[str]: ...
    def __getattr__(self, name: str) -> Any: ...

    # ingestion
    def register(self, name: str, obj: Any, *, persist: bool = False) -> Connection: ...
    def append(self, name: str, obj: Any) -> Connection: ...
    def unregister(self, name: str) -> Connection: ...

    # beacon extras
    def json_query(self, spec: dict[str, Any]) -> Result: ...
    def functions(self) -> Relation: ...
    def metrics(self, query_id: str | None = None) -> Relation: ...
    def list_tables(self) -> list[str]: ...
    def refresh(self, name: str) -> Connection: ...

    # identity / session
    def cursor(self) -> Connection: ...
    def connect_as(
        self, username: str | None = None, password: str | None = None, token: str | None = None
    ) -> Connection: ...
    def as_anonymous(self) -> Connection: ...
    def whoami(self) -> dict[str, Any]: ...
    @property
    def auth_enabled(self) -> bool: ...

    # transactions (autocommit — these are no-ops, for DB-API/SQLAlchemy compatibility)
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

    # lifecycle
    def close(self) -> None: ...
    def __enter__(self) -> Connection: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...

# ---------------------------------------------------------------------------------------------
# Module-level functions
# ---------------------------------------------------------------------------------------------

def connect(
    database: str = ":memory:",
    *,
    read_only: bool = False,
    auth: bool = False,
    username: str | None = None,
    password: str | None = None,
    token: str | None = None,
    admin_username: str | None = None,
    admin_password: str | None = None,
    anonymous: bool = True,
    datasets: str | None = None,
    batch_size: int | None = None,
    memory_limit: int | None = None,
    cpu_limit: int | None = None,
    crawlers: bool = False,
    secrets_key: str | None = None,
) -> Connection: ...
def engine_version() -> str: ...
