[package]
name = "beacon-erddap"
version.workspace = true
edition = "2024"

rust-version.workspace = true

[dependencies]
beacon-arrow-netcdf = { path = "../beacon-arrow-netcdf" }
beacon-common = { path = "../../beacon-common" }
beacon-datafusion-ext = { path = "../../beacon-datafusion-ext" }
beacon-nd-array = { path = "../beacon-nd-array" }

arrow = { workspace = true }
datafusion = { workspace = true }
object_store = { workspace = true }
parquet = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
percent-encoding = "2"
reqwest = { workspace = true, features = ["stream"] }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
typetag = { workspace = true }
url = { workspace = true }
