[package]
name = "beacon-tables"
version = "1.1.0"
edition = "2021"

[dependencies]
arrow = {workspace = true}
indexmap = { workspace = true }
thiserror = { workspace = true }
typetag =  { workspace=true}
async-trait = { workspace=true}
datafusion = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
parking_lot = { workspace = true}
tokio = { workspace = true }
tracing = { workspace = true }

beacon-sources = { path = "../beacon-sources" }
beacon-config = { path = "../beacon-config" }
beacon-query = { path = "../beacon-query" }
beacon-common = { path = "../beacon-common" }