[package]
name = "beacon-index"
version = "0.1.0"
edition = "2021"

[dependencies]
typetag = "0.2.20"
serde = { workspace=true }
async-trait = { workspace=true }
datafusion = { workspace=true }
arrow = { workspace=true }
anyhow = { workspace=true}