[package]
name = "beacon-logger"
version = "1.0.0"
edition = "2021"

[dependencies]
console = "0.15.7"
chrono = "0.4.24"
log = "0.4.17"
rolling-file = "0.2.0"

lazy_static = "1.4.0"

# Local dependencies
beacon-config = { path = "../beacon-config" }