name: "Nightly Build"

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate date tag
              id: tag
              run: echo "DATE_TAG=nightly-$(date +'%Y%m%d')" >> $GITHUB_ENV

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/my-image:nightly
                      ghcr.io/${{ github.repository_owner }}/my-image:${{ env.DATE_TAG }}

            - name: Create GitHub Release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.DATE_TAG }}
                  release_name: Nightly Build ${{ env.DATE_TAG }}
                  draft: false
                  prerelease: true
